name: CI
on:
  pull_request:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup JDK
        uses: olafurpg/setup-scala@v11
        with:
          java-version: adopt@1.11
      - name: Coursier cache
        uses: coursier/cache-action@v6
      - name: Compile
        run: sbt compile
      - name: Test
        run: sbt test
          - uses: dorny/test-reporter@v1
               with:
                 artifact: test-results            # artifact name
                 name: Scala Tests                  # Name of the check run which will be created
                 path: '**/test-reports/*.xml'                     # Path to test results (inside artifact .zip)
                 reporter: java-junit

